import JudgeCore
import JudgeTargets
import JudgeAliases

set_option autoImplicit false
set_option warningAsError true

open Lean Elab Command
run_cmd liftTermElabM do
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.order_iff_dnf ``PidSxDnfOrderJudgeAliases.order_iff_dnf
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.antichain_antisymm ``PidSxDnfOrderJudgeAliases.antichain_antisymm
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.dnf_injective_on_antichains ``PidSxDnfOrderJudgeAliases.dnf_injective_on_antichains
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.source_event_iff_dnf ``PidSxDnfOrderJudgeAliases.source_event_iff_dnf
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.order_implies_source_event_subset ``PidSxDnfOrderJudgeAliases.order_implies_source_event_subset
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.order_iff_implication_on_realizing_domain ``PidSxDnfOrderJudgeAliases.order_iff_implication_on_realizing_domain
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.alternate_values_realize_all_patterns ``PidSxDnfOrderJudgeAliases.alternate_values_realize_all_patterns
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.source_event_injective_on_realizing_domain ``PidSxDnfOrderJudgeAliases.source_event_injective_on_realizing_domain
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.order_implies_target_restricted_subset ``PidSxDnfOrderJudgeAliases.order_implies_target_restricted_subset
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.singleton_event_collision ``PidSxDnfOrderJudgeAliases.singleton_event_collision
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.singleton_not_all_patterns ``PidSxDnfOrderJudgeAliases.singleton_not_all_patterns
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.binary_diagonal_collision ``PidSxDnfOrderJudgeAliases.binary_diagonal_collision
  PidSxDnfOrderJudge.checkContractView ``PidSxDnfOrderJudgeTargets.antichain_premise_is_load_bearing ``PidSxDnfOrderJudgeAliases.antichain_premise_is_load_bearing
